### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by cnhx** [o24/atom-open-marked#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-open-marked](https://github.com/o24/atom-open-marked) package, v0.12.0
### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/huaxia/.atom/packages/atom-open-marked/lib/atom-open-marked.coffee:22

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.AtomOpenMarked.openMarked (/Users/huaxia/.atom/packages/atom-open-marked/lib/atom-open-marked.coffee:22:26)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-open-marked:OpenMarked (/Users/huaxia/.atom/packages/atom-open-marked/lib/atom-open-marked.coffee:14:95)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:15.9.0 markdown-preview:toggle (atom-text-editor.editor)
     -1:07.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:06.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.7.0 editor:newline (atom-text-editor.editor.is-focused)
 22x -1:04.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:52.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.7.0 settings-view:open (a.inline-block)
     -0:29.5.0 command-palette:toggle (div.panels)
     -0:21.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 atom-open-marked:OpenMarked (div.panels)
     -0:05.1.0 command-palette:toggle (div.panels)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 atom-open-marked:OpenMarked (div.panels)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".meta"
    ],
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-open-marked, v0.12.0
language-markdown, v0.8.1
markdown-preview-plus, v2.2.2
minimap, v4.19.0
simplified-chinese-menu, v3.4.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by homebysix** [comment]
For me, these steps reliably reproduce:

1. Open a project folder that includes at least one Markdown file.
2. Single-click on the Markdown file in the project tree on the left.
3. Trigger Open-Marked via menu or shortcut, observe error.

Workarounds include:

- double-click on the Markdown file to "pin" its buffer to the project window, or
- click in the text buffer at least once prior to invoking the Open-Marked shortcut.

You can tell the error will happen upon invocation if the Atom title bar starts with "Project" instead of the name of the file.
